### ISSUE TITLE
Site deployment.

### ISSUE THREAD

**Issue by dev1abhi** [devrihan/Gym-Landing-Page#1]
Bro , Release section re site link de.

**Comment by devrihan** [comment]
Haven't made it fully responsive, after making it i will

**Comment by devrihan** [comment]
https://www.linkedin.com/posts/sk-rihan-akhtar-27a1a3248_just-started-with-web-developement-and-here-activity-7098407213848793089-iYKU?utm_source=share&utm_medium=member_android
